version: '3'

services:

  nginx:
    image: nginx
    container_name: vagrant_nginx
    restart: always
    ports:
      - "8383:80"
    volumes:
      - ./vm-practice:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - postgres

  apache:
    build:
      context: ./apache
    container_name: vagrant_apache
    restart: always
    ports:
      - "8282:80"
      - "443:443"
    volumes:
      - ./vm-practice:/var/www
      - ./apache/apache2.conf:/etc/apache2/sites-enabled/000-default.conf
    links:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: vagrant_mysql
    environment:
      - MYSQL_DATABASE=project1
      - MYSQL_USER=giztech
      - MYSQL_PASSWORD=gizumo
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION --character-set-server=utf8 --collation-server=utf8_unicode_ci

  postgres:
    image: postgres:11
    container_name: vagrant_postgres
    restart: always
    environment:
      - POSTGRES_DB=project2
      - POSTGRES_USER=giztech
      - POSTGRES_PASSWORD=gizumo
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgres

  php-fpm:
    build:
      context: ./php-fpm
    container_name: php-fpm
    restart: always
    volumes:
      - ./vm-practice:/var/www
    links:
      - postgres

volumes:
  db:
